version: '3.2'
services:
  postgres:
    image: jetherrodrigues/postgres-postgis:9.6-2.5
    environment:
      POSTGRES_PASSWORD: "Unisal2019!"
    ports:
      - "15432:5432"
    volumes:
      - postgresdb:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "minicurso@dev.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "5555:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

volumes:
  postgresdb:

networks: 
  postgres-compose-network:
    driver: bridge